-- phase - 1: exploratory analysis
-- total revenue generated by food delivery app
select sum(order_amount - discount) as total_revenue 
from orders;
-- total orders per city
select R.city,count(*) as total_orders
from orders o
join restaurants r on o.restaurant_id = r.restaurant_id
group by r.city
order by total_orders desc;
-- top 10 customers by spending

-- customer segmentation

-- customer categoy (gold, silver, bronze)

-- phase - 3: restaurant performance

-- top 10 restaurants by revenue
select r.restaurant_id,
r.restaurant_name,
r.city,
sum(o.order_amount - o.discount) as total_revenue
from orders o
join restaurants r on o.restaurant_id = r.restaurant_id
group by r.restaurant_name,r.restaurant_id,r.city
order by total_revenue desc
limit 10;
-- avg rating vs revenue

-- phase - 4: delivery analysis
-- avg delivery time per city
select r.city,avg(delivery_time) as avg_delivery_time
from orders o
join restaurants r on o.restaurant_id = r.restaurant_id
group by r.city
order by avg_delivery_time;
-- late del (above 45 mins)
-- phase - 5: payment and disc analysis
-- payment method distribution
select payment_method,count(*) as count
from orders
group by payment_method
order by count desc;
-- discount impact on revenue

-- phase - 6: adv sql

-- monthly revenue using cte
with monthly_revenue as (
    select 
    month(order_date) as month,
    sum(order_amount - discount) as revenue
    from orders
    group by month
)
select month,revenue
from monthly_revenue
order by month;

-- 12

-- 13

-- phase 7
-- create revenue view
create view revenue_view as
select 
r.restaurant_id,
r.restaurant_name,
r.city,
sum(o.order_amount - o.discount) as total_revenue
from orders o
join restaurants r on o.restaurant_id = r.restaurant_id
group by r.restaurant_name,r.restaurant_id,r.city;